package org.homepoker.model.user;

import lombok.Value;

/**
 * The domain object represents a request to change a user's password.
 *
 * @param loginId       This is the existing user's ID
 * @param userChallenge The user challenge is either the user's existing password or a time-sensitive code generated by the server and sent to the user's email account.
 * @param newPassword   The new password.
 */
public record UserPasswordChangeRequest(String loginId, String userChallenge, String newPassword) {
}
