/**
 * Game events received from the server via WebSocket.
 * All events use `eventType` as the discriminator (kebab-case).
 *
 * Seat positions are 1-indexed (range 1..numberOfSeats), matching the server wire format.
 */

import { Card } from '../poker/poker-models';
import { GameStatus, HandPhase, Player, Pot, SeatCard, Table, TableStatus } from './game-models';
import { PlayerAction } from './game-commands';

// --- Game-Level Events ---

export type MessageSeverity = 'INFO' | 'WARNING' | 'ERROR';

export { HandPhase, SeatCard };

/** Codified per-hand status of a seat. */
export type HandPlayerStatus =
  | 'WAITING'
  | 'ACTIVE'
  | 'TO_ACT'
  | 'FOLDED'
  | 'ALL_IN'
  | 'SITTING_OUT';

/** Compact per-seat snapshot embedded in table events (HandStarted, BettingRoundComplete). */
export interface SeatSummary {
  seatPosition: number;
  userId: string | null;
  status: HandPlayerStatus;
  chipCount: number;
  currentBetAmount: number;
}

export interface GameStatusChangedEvent {
  eventType: 'game-status-changed';
  timestamp: string;
  gameId: string;
  oldStatus: GameStatus;
  newStatus: GameStatus;
}

export interface GameMessageEvent {
  eventType: 'game-message';
  timestamp: string;
  gameId: string;
  message: string;
}

/**
 * Client-side synthetic variant of GameMessageEvent. Used for messages
 * generated by the client (action history, winner announcements) to carry
 * an optional `kind` discriminator for distinct rendering. Real server
 * `game-message` events have `kind === undefined`.
 */
export interface ClientGameMessage extends GameMessageEvent {
  kind?: 'action' | 'showdown';
}

export interface PlayerBuyInEvent {
  eventType: 'player-buy-in';
  timestamp: string;
  gameId: string;
  userId: string;
  amount: number;
  newChipCount: number;
}

export interface PlayerJoinedEvent {
  eventType: 'player-joined';
  timestamp: string;
  gameId: string;
  userId: string;
}

export interface PlayerSeatedEvent {
  eventType: 'player-seated';
  timestamp: string;
  gameId: string;
  userId: string;
  tableId: string;
}

export interface PlayerMovedTablesEvent {
  eventType: 'player-moved-tables';
  timestamp: string;
  gameId: string;
  userId: string;
  fromTableId: string | null;
  toTableId: string;
}

export interface PlayerDisconnectedEvent {
  eventType: 'player-disconnected';
  timestamp: string;
  gameId: string;
  userId: string;
}

export interface PlayerReconnectedEvent {
  eventType: 'player-reconnected';
  timestamp: string;
  gameId: string;
  userId: string;
}

export interface AdminViewingReplayEvent {
  eventType: 'admin-viewing-replay';
  timestamp: string;
  gameId: string;
  adminUserId: string;
  adminAlias: string;
  tableId: string;
  handNumber: number;
}

// --- Table-Level Events ---

export interface TableStatusChangedEvent {
  eventType: 'table-status-changed';
  timestamp: string;
  gameId: string;
  tableId: string;
  oldStatus: TableStatus;
  newStatus: TableStatus;
}

export interface HandPhaseChangedEvent {
  eventType: 'hand-phase-changed';
  timestamp: string;
  gameId: string;
  tableId: string;
  oldPhase: HandPhase;
  newPhase: HandPhase;
}

export interface WaitingForPlayersEvent {
  eventType: 'waiting-for-players';
  timestamp: string;
  gameId: string;
  tableId: string;
  activePlayers: number;
  seatedPlayers: number;
}

export type BlindType = 'SMALL' | 'BIG';

export interface BlindPostedEvent {
  eventType: 'blind-posted';
  timestamp: string;
  gameId: string;
  tableId: string;
  seatPosition: number;
  userId: string;
  blindType: BlindType;
  amountPosted: number;
}

export interface HandStartedEvent {
  eventType: 'hand-started';
  timestamp: string;
  gameId: string;
  tableId: string;
  handNumber: number;
  dealerPosition: number;
  smallBlindPosition: number;
  bigBlindPosition: number;
  smallBlindAmount: number;
  bigBlindAmount: number;
  currentBet: number;
  minimumRaise: number;
  seats: SeatSummary[];
}

export interface HoleCardsDealtEvent {
  eventType: 'hole-cards-dealt';
  timestamp: string;
  gameId: string;
  tableId: string;
  userId: string;
  seatPosition: number;
  cards: SeatCard[];
  seatsWithCards: number[];
}

export interface CommunityCardsDealtEvent {
  eventType: 'community-cards-dealt';
  timestamp: string;
  gameId: string;
  tableId: string;
  cards: Card[];
  phase: HandPhase;
  allCommunityCards: Card[];
}

export interface PlayerActedEvent {
  eventType: 'player-acted';
  timestamp: string;
  gameId: string;
  tableId: string;
  seatPosition: number;
  userId: string;
  action: PlayerAction;
  chipCount: number;
  resultingStatus: HandPlayerStatus;
  currentBet: number;
  minimumRaise: number;
  potTotal: number;
}

export interface PlayerTimedOutEvent {
  eventType: 'player-timed-out';
  timestamp: string;
  gameId: string;
  tableId: string;
  seatPosition: number;
  userId: string;
  defaultAction: PlayerAction;
}

export interface ActionOnPlayerEvent {
  eventType: 'action-on-player';
  timestamp: string;
  gameId: string;
  tableId: string;
  seatPosition: number;
  userId: string;
  actionDeadline: string;
  currentBet: number;
  minimumRaise: number;
  callAmount: number;
  playerChipCount: number;
  potTotal: number;
}

export interface BettingRoundCompleteEvent {
  eventType: 'betting-round-complete';
  timestamp: string;
  gameId: string;
  tableId: string;
  completedPhase: HandPhase;
  pots: Pot[];
  seats: SeatSummary[];
  potTotal: number;
}

export interface Winner {
  seatPosition: number;
  userId: string;
  amount: number;
  handDescription: string;
  /**
   * The concrete cards (value + suit) forming the winner's best five-card hand,
   * so clients can highlight them. Empty when the pot was won without a showdown
   * (e.g. everyone else folded). Matches the server `showdown-result` payload.
   */
  winningCards: Card[];
}

export interface PotResult {
  potIndex: number;
  potAmount: number;
  winners: Winner[];
}

export interface ShowdownResultEvent {
  eventType: 'showdown-result';
  timestamp: string;
  gameId: string;
  tableId: string;
  potResults: PotResult[];
}

export interface HandCompleteEvent {
  eventType: 'hand-complete';
  timestamp: string;
  gameId: string;
  tableId: string;
  handNumber: number;
}

// --- User Events ---

export interface UserMessageEvent {
  eventType: 'user-message';
  timestamp: string;
  userId: string;
  severity: MessageSeverity;
  message: string;
}

// --- Snapshot Events ---

export interface GameSnapshotEvent {
  eventType: 'game-snapshot';
  timestamp: string;
  userId: string;
  gameId: string;
  gameName: string;
  status: GameStatus;
  startTime: string;
  smallBlind: number;
  bigBlind: number;
  players: Player[];
  tableIds: string[];
}

export interface TableSnapshotEvent {
  eventType: 'table-snapshot';
  timestamp: string;
  userId: string;
  gameId: string;
  table: Table;
}

// --- Discriminated Union ---

export type GameEvent =
  | GameStatusChangedEvent
  | GameMessageEvent
  | PlayerJoinedEvent
  | PlayerSeatedEvent
  | PlayerBuyInEvent
  | PlayerMovedTablesEvent
  | PlayerDisconnectedEvent
  | PlayerReconnectedEvent
  | AdminViewingReplayEvent
  | TableStatusChangedEvent
  | HandPhaseChangedEvent
  | WaitingForPlayersEvent
  | HandStartedEvent
  | BlindPostedEvent
  | HoleCardsDealtEvent
  | CommunityCardsDealtEvent
  | PlayerActedEvent
  | PlayerTimedOutEvent
  | ActionOnPlayerEvent
  | BettingRoundCompleteEvent
  | ShowdownResultEvent
  | HandCompleteEvent
  | UserMessageEvent
  | GameSnapshotEvent
  | TableSnapshotEvent;
